// <auto-generated />
namespace WizBooklat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class loaniscancelled : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(loaniscancelled));
        
        string IMigrationMetadata.Id
        {
            get { return "202008200551176_loan is cancelled"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
