// <auto-generated />
namespace WizBooklat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class neweditionbooktemplateid : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(neweditionbooktemplateid));
        
        string IMigrationMetadata.Id
        {
            get { return "202009060747287_new edition book template id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
