// <auto-generated />
namespace WizBooklat.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addmobilenumberandaccounttype : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addmobilenumberandaccounttype));
        
        string IMigrationMetadata.Id
        {
            get { return "202007200529435_Add mobile number and account type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
